//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.2034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stGeo.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("stGeo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Geo base not found records.
        /// </summary>
        public static string GeoBaseEmpty {
            get {
                return ResourceManager.GetString("GeoBaseEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading GeoBase: {0}, please wait...
        /// </summary>
        public static string GeoBaseLoad {
            get {
                return ResourceManager.GetString("GeoBaseLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no data index for this Geo Provider found.
        /// </summary>
        public static string GeoErrorIndex {
            get {
                return ResourceManager.GetString("GeoErrorIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на key is not defined for this Geo Provider.
        /// </summary>
        public static string GeoErrorKeyEmpty {
            get {
                return ResourceManager.GetString("GeoErrorKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Geo MaxMind source: File not found &apos;{0}&apos;.
        /// </summary>
        public static string GeoMaxMindFileNotFound {
            get {
                return ResourceManager.GetString("GeoMaxMindFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Geo MaxMind data: list is empty &apos;{0}&apos;.
        /// </summary>
        public static string GeoMaxMindListEmpty {
            get {
                return ResourceManager.GetString("GeoMaxMindListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на this option not support for this version server software.
        /// </summary>
        public static string GeoNotSupport {
            get {
                return ResourceManager.GetString("GeoNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на      Parse GEO ASN Data: .
        /// </summary>
        public static string GeoPbASN {
            get {
                return ResourceManager.GetString("GeoPbASN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на      Parse GEO Country Data: .
        /// </summary>
        public static string GeoPbCountry {
            get {
                return ResourceManager.GetString("GeoPbCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на      Merge GEO Data: .
        /// </summary>
        public static string GeoPbMerge {
            get {
                return ResourceManager.GetString("GeoPbMerge", resourceCulture);
            }
        }
    }
}
