//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.2034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stGeo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string>5jVVtbLUJnjEIyII17ZlKzwkEi2gwqMB</string>
  <string />
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection stGeoKey {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["stGeoKey"]));
            }
            set {
                this["stGeoKey"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string>https://developer.mapquest.com/plan_purchase/steps/business_edition/business_edition_free/register</string>
  <string>https://tech.yandex.ru/maps/</string>
  <string>https://developers.google.com/maps/documentation/static-maps/get-api-key</string>
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection stGeoHelpURL {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["stGeoHelpURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string />
  <string>https://www.mapquestapi.com/staticmap/v4/getplacemap</string>
  <string>https://static-maps.yandex.ru/1.x/</string>
  <string>https://maps.googleapis.com/maps/api/staticmap</string>
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection stGeoURL {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["stGeoURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>false</string>
  <string>true</string>
  <string>false</string>
  <string>true</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection stGeoKeyRequire {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["stGeoKeyRequire"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GeoIPASNum2.csv")]
        public string stFileMaxMindASN {
            get {
                return ((string)(this["stFileMaxMindASN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GeoIPCountryWhois.csv")]
        public string stFileMaxMindCountry {
            get {
                return ((string)(this["stFileMaxMindCountry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stGeoData.bin")]
        public string stFileGeoData {
            get {
                return ((string)(this["stFileGeoData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AS")]
        public string stMaxMindASNPrefix {
            get {
                return ((string)(this["stMaxMindASNPrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GeoIPASNum2.zip")]
        public string stZipFileMaxMindASN {
            get {
                return ((string)(this["stZipFileMaxMindASN"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GeoIPCountryCSV.zip")]
        public string stZipFileMaxMindCountry {
            get {
                return ((string)(this["stZipFileMaxMindCountry"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://geolite.maxmind.com/download/geoip/database/")]
        public string stMaxMindDownloadCountryURL {
            get {
                return ((string)(this["stMaxMindDownloadCountryURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://download.maxmind.com/download/geoip/database/asnum/")]
        public string stMaxMindDownloadASNURL {
            get {
                return ((string)(this["stMaxMindDownloadASNURL"]));
            }
        }
    }
}
