//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.2034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stCoCAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("stCoCAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bgClanTemplate {
            get {
                object obj = ResourceManager.GetObject("bgClanTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bgDefaultBage {
            get {
                object obj = ResourceManager.GetObject("bgDefaultBage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bgDefaultLeague {
            get {
                object obj = ResourceManager.GetObject("bgDefaultLeague", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bgMemberTemplate {
            get {
                object obj = ResourceManager.GetObject("bgMemberTemplate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bgTemplate404Error300x180 {
            get {
                object obj = ResourceManager.GetObject("bgTemplate404Error300x180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bgTemplate404Error500x100 {
            get {
                object obj = ResourceManager.GetObject("bgTemplate404Error500x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bgTemplate404MembrsError300x180 {
            get {
                object obj = ResourceManager.GetObject("bgTemplate404MembrsError300x180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bgTemplate500Error300x180 {
            get {
                object obj = ResourceManager.GetObject("bgTemplate500Error300x180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bgTemplate500Error500x100 {
            get {
                object obj = ResourceManager.GetObject("bgTemplate500Error500x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bgTemplate500NoSupportError300x180 {
            get {
                object obj = ResourceManager.GetObject("bgTemplate500NoSupportError300x180", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bgTemplate500NoSupportError500x100 {
            get {
                object obj = ResourceManager.GetObject("bgTemplate500NoSupportError500x100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_0 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_1 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_10 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_11 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_12 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_13 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_14 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_15 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_16 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_17 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_18 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_19 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_2 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_20 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_21 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_22 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_23 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_24 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_25 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_3 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_4 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_5 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_6 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_7 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_8 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClanTmpl_9 {
            get {
                object obj = ResourceManager.GetObject("ClanTmpl_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan ID is empty or not defined.
        /// </summary>
        internal static string CoCClanIdEmpty {
            get {
                return ResourceManager.GetString("CoCClanIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan Tag empty.
        /// </summary>
        internal static string CoCClanTagEmpty {
            get {
                return ResourceManager.GetString("CoCClanTagEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: parse cmd incorrect length.
        /// </summary>
        internal static string CoCDBExceptionLength {
            get {
                return ResourceManager.GetString("CoCDBExceptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get URL Json source is empty: {0}.
        /// </summary>
        internal static string CoCGetUrlEmpty {
            get {
                return ResourceManager.GetString("CoCGetUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CoC API server: &apos;{0}&apos;, {1}.
        /// </summary>
        internal static string CoCGetUrlServerError {
            get {
                return ResourceManager.GetString("CoCGetUrlServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Informer error]: {0}.
        /// </summary>
        internal static string CoCInformerError {
            get {
                return ResourceManager.GetString("CoCInformerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Init {0} instance error: {1}.
        /// </summary>
        internal static string CoCInitError {
            get {
                return ResourceManager.GetString("CoCInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на API key empty or not found, (see https://developer.clashofclans.com/).
        /// </summary>
        internal static string CoCKeyEmpty {
            get {
                return ResourceManager.GetString("CoCKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update image: {0}{1}.
        /// </summary>
        internal static string CoCMediaDownloadInfo {
            get {
                return ResourceManager.GetString("CoCMediaDownloadInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add client.
        /// </summary>
        internal static string CoCNotifyAddClient {
            get {
                return ResourceManager.GetString("CoCNotifyAddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add data table.
        /// </summary>
        internal static string CoCNotifyAddDataTable {
            get {
                return ResourceManager.GetString("CoCNotifyAddDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (see last error..).
        /// </summary>
        internal static string CoCNotifyDataOtherError {
            get {
                return ResourceManager.GetString("CoCNotifyDataOtherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Make RSS feed.
        /// </summary>
        internal static string CoCNotifyDataRss {
            get {
                return ResourceManager.GetString("CoCNotifyDataRss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data send.
        /// </summary>
        internal static string CoCNotifyDataSseSend {
            get {
                return ResourceManager.GetString("CoCNotifyDataSseSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notfy DEBUG SSE, client {0}/Dispose: {1}.
        /// </summary>
        internal static string CoCNotifyDisposeError {
            get {
                return ResourceManager.GetString("CoCNotifyDisposeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Host/Data count.
        /// </summary>
        internal static string CoCNotifyHostDataCount {
            get {
                return ResourceManager.GetString("CoCNotifyHostDataCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notify DEBUG SSE, Last Ip: {0}, {1} - {2}.
        /// </summary>
        internal static string CoCNotifyProcessDebug {
            get {
                return ResourceManager.GetString("CoCNotifyProcessDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notify  DEBUG SSE, {0} error: {1} - {2}.
        /// </summary>
        internal static string CoCNotifyProcessError {
            get {
                return ResourceManager.GetString("CoCNotifyProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (c) stCoCServer RSS feed.
        /// </summary>
        internal static string CoCNotifyRssCopy {
            get {
                return ResourceManager.GetString("CoCNotifyRssCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan #{0} updated statistic time line (RSS feed). Create: {1}.
        /// </summary>
        internal static string CoCNotifyRssDesc {
            get {
                return ResourceManager.GetString("CoCNotifyRssDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CoC notify update time line.
        /// </summary>
        internal static string CoCNotifyRssTitle {
            get {
                return ResourceManager.GetString("CoCNotifyRssTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send part.
        /// </summary>
        internal static string CoCNotifySendPart {
            get {
                return ResourceManager.GetString("CoCNotifySendPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set header.
        /// </summary>
        internal static string CoCNotifySetHeader {
            get {
                return ResourceManager.GetString("CoCNotifySetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request ID is wrong or not defined.
        /// </summary>
        internal static string CoCRequestIdEmpty {
            get {
                return ResourceManager.GetString("CoCRequestIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CoC API URL create error, URL empty.
        /// </summary>
        internal static string CoCUrlEmpty {
            get {
                return ResourceManager.GetString("CoCUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Curl instance is empty.
        /// </summary>
        internal static string CurlObjEmpty {
            get {
                return ResourceManager.GetString("CurlObjEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Get json unknown error.
        /// </summary>
        internal static string CurlReturnReason {
            get {
                return ResourceManager.GetString("CurlReturnReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty input Json Data: {0} Table.
        /// </summary>
        internal static string DataTableEmptyIn {
            get {
                return ResourceManager.GetString("DataTableEmptyIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan {0} change Level: {1} -&gt; {2}{3}.
        /// </summary>
        internal static string fmtNotifyClanChangeLevel {
            get {
                return ResourceManager.GetString("fmtNotifyClanChangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan {0} change Members: {1}{2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyClanChangeMembers {
            get {
                return ResourceManager.GetString("fmtNotifyClanChangeMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan {2} change Name: {3}.
        /// </summary>
        internal static string fmtNotifyClanChangeName {
            get {
                return ResourceManager.GetString("fmtNotifyClanChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan {0} change Points: {1}{2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyClanChangePoints {
            get {
                return ResourceManager.GetString("fmtNotifyClanChangePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan {0} change Trophies: {1}{2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyClanChangeTrophies {
            get {
                return ResourceManager.GetString("fmtNotifyClanChangeTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan {0} change Type: {2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyClanChangeType {
            get {
                return ResourceManager.GetString("fmtNotifyClanChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan {0} change WarFrequency: {2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyClanChangeWarFrequency {
            get {
                return ResourceManager.GetString("fmtNotifyClanChangeWarFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan {0} change WarPublic: {2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyClanChangeWarPublic {
            get {
                return ResourceManager.GetString("fmtNotifyClanChangeWarPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan {0} change WarSeries: {1}{2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyClanChangeWarSeries {
            get {
                return ResourceManager.GetString("fmtNotifyClanChangeWarSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan {0} change WarWin: {1}{2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyClanChangeWarWin {
            get {
                return ResourceManager.GetString("fmtNotifyClanChangeWarWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Available {0} update in clan, modified time: {1}, next: {2}.
        /// </summary>
        internal static string fmtNotifyHeaderCount {
            get {
                return ResourceManager.GetString("fmtNotifyHeaderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - change Donation Receive {1}{2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyMemberChangeDonationReceive {
            get {
                return ResourceManager.GetString("fmtNotifyMemberChangeDonationReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - change Donation Send: {1}{2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyMemberChangeDonationSend {
            get {
                return ResourceManager.GetString("fmtNotifyMemberChangeDonationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - change League: {2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyMemberChangeLeague {
            get {
                return ResourceManager.GetString("fmtNotifyMemberChangeLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - change Level: {1}{2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyMemberChangeLevel {
            get {
                return ResourceManager.GetString("fmtNotifyMemberChangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {2} - change Nik: {3}.
        /// </summary>
        internal static string fmtNotifyMemberChangeNik {
            get {
                return ResourceManager.GetString("fmtNotifyMemberChangeNik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - change Role: {2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyMemberChangeRole {
            get {
                return ResourceManager.GetString("fmtNotifyMemberChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} - change Trophies: {1}{2} -&gt; {3}.
        /// </summary>
        internal static string fmtNotifyMemberChangeTrophies {
            get {
                return ResourceManager.GetString("fmtNotifyMemberChangeTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Member {0} left clan.
        /// </summary>
        internal static string fmtNotifyMemberExit {
            get {
                return ResourceManager.GetString("fmtNotifyMemberExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New member {0}.
        /// </summary>
        internal static string fmtNotifyMemberNew {
            get {
                return ResourceManager.GetString("fmtNotifyMemberNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} {1}.
        /// </summary>
        internal static string fmtNotifyRssItemTitle {
            get {
                return ResourceManager.GetString("fmtNotifyRssItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan war end: {0} {2}%-{3}% : {1}{4}.
        /// </summary>
        internal static string fmtNotifyWarClanEnd {
            get {
                return ResourceManager.GetString("fmtNotifyWarClanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  vs .
        /// </summary>
        internal static string fmtNotifyWarClanEndVs {
            get {
                return ResourceManager.GetString("fmtNotifyWarClanEndVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum Clan points: @0@r.
        /// </summary>
        internal static string fmtRrdClanChangePointsMax {
            get {
                return ResourceManager.GetString("fmtRrdClanChangePointsMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum Clan points: @0@r.
        /// </summary>
        internal static string fmtRrdClanChangePointsMin {
            get {
                return ResourceManager.GetString("fmtRrdClanChangePointsMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan change Points.
        /// </summary>
        internal static string fmtRrdClanChangePointsTitle {
            get {
                return ResourceManager.GetString("fmtRrdClanChangePointsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на clan points.
        /// </summary>
        internal static string fmtRrdClanChangePointsVlabel {
            get {
                return ResourceManager.GetString("fmtRrdClanChangePointsVlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum wars win: @0@r.
        /// </summary>
        internal static string fmtRrdClanChangeWarWinMax {
            get {
                return ResourceManager.GetString("fmtRrdClanChangeWarWinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum wars win: @0@r.
        /// </summary>
        internal static string fmtRrdClanChangeWarWinMin {
            get {
                return ResourceManager.GetString("fmtRrdClanChangeWarWinMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan War wins.
        /// </summary>
        internal static string fmtRrdClanChangeWarWinTitle {
            get {
                return ResourceManager.GetString("fmtRrdClanChangeWarWinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на war wins.
        /// </summary>
        internal static string fmtRrdClanChangeWarWinVlabel {
            get {
                return ResourceManager.GetString("fmtRrdClanChangeWarWinVlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum receive donation: @0@r.
        /// </summary>
        internal static string fmtRrdMemberChangeDonationReceiveMax {
            get {
                return ResourceManager.GetString("fmtRrdMemberChangeDonationReceiveMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum receive donation: @0@r.
        /// </summary>
        internal static string fmtRrdMemberChangeDonationReceiveMin {
            get {
                return ResourceManager.GetString("fmtRrdMemberChangeDonationReceiveMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan Donation receive.
        /// </summary>
        internal static string fmtRrdMemberChangeDonationReceiveTitle {
            get {
                return ResourceManager.GetString("fmtRrdMemberChangeDonationReceiveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на receive troops.
        /// </summary>
        internal static string fmtRrdMemberChangeDonationReceiveVlabel {
            get {
                return ResourceManager.GetString("fmtRrdMemberChangeDonationReceiveVlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum send donation: @0@r.
        /// </summary>
        internal static string fmtRrdMemberChangeDonationSendMax {
            get {
                return ResourceManager.GetString("fmtRrdMemberChangeDonationSendMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum send donation: @0@r.
        /// </summary>
        internal static string fmtRrdMemberChangeDonationSendMin {
            get {
                return ResourceManager.GetString("fmtRrdMemberChangeDonationSendMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan Donation send.
        /// </summary>
        internal static string fmtRrdMemberChangeDonationSendTitle {
            get {
                return ResourceManager.GetString("fmtRrdMemberChangeDonationSendTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на send troops.
        /// </summary>
        internal static string fmtRrdMemberChangeDonationSendVlabel {
            get {
                return ResourceManager.GetString("fmtRrdMemberChangeDonationSendVlabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_0 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_1 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_10 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_11 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_12 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_13 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_14 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_15 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_2 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_3 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_4 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_5 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_6 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_7 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_8 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MembersTmpl_9 {
            get {
                object obj = ResourceManager.GetObject("MembersTmpl_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RrdBgClanChangePoints {
            get {
                object obj = ResourceManager.GetObject("RrdBgClanChangePoints", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RrdBgClanChangeWarWin {
            get {
                object obj = ResourceManager.GetObject("RrdBgClanChangeWarWin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RrdBgMemberChangeDonationSend {
            get {
                object obj = ResourceManager.GetObject("RrdBgMemberChangeDonationSend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Day.
        /// </summary>
        internal static string RrdPeriodNameDay {
            get {
                return ResourceManager.GetString("RrdPeriodNameDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Month.
        /// </summary>
        internal static string RrdPeriodNameMonth {
            get {
                return ResourceManager.GetString("RrdPeriodNameMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Week.
        /// </summary>
        internal static string RrdPeriodNameWeek {
            get {
                return ResourceManager.GetString("RrdPeriodNameWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Year.
        /// </summary>
        internal static string RrdPeriodNameYear {
            get {
                return ResourceManager.GetString("RrdPeriodNameYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Canceled update CoC DB: [{0}].
        /// </summary>
        internal static string ShedCanceledProcess {
            get {
                return ResourceManager.GetString("ShedCanceledProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next update CoC DB:  [{0}].
        /// </summary>
        internal static string ShedNextProcess {
            get {
                return ResourceManager.GetString("ShedNextProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start update CoC DB: [{0}].
        /// </summary>
        internal static string ShedStartProcess {
            get {
                return ResourceManager.GetString("ShedStartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stop update CoC DB: [{0}].
        /// </summary>
        internal static string ShedStopProcess {
            get {
                return ResourceManager.GetString("ShedStopProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End  update CoC DB:  [{0} sec].
        /// </summary>
        internal static string ShedWaitProcess {
            get {
                return ResourceManager.GetString("ShedWaitProcess", resourceCulture);
            }
        }
    }
}
