//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.2034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stCoCAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT name FROM sqlite_master WHERE type=\'table\' ORDER BY name;")]
        public string DBTableList {
            get {
                return ((string)(this["DBTableList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AND year = {0} AND season = {1}")]
        public string DBWhereDate {
            get {
                return ((string)(this["DBWhereDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM clan")]
        public string DBSelectClanInfo {
            get {
                return ((string)(this["DBSelectClanInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT *  FROM clanmembers WHERE status = {0}")]
        public string DBSelectMember {
            get {
                return ((string)(this["DBSelectMember"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AND tag = \'{0}\'")]
        public string DBSelectMemberTag {
            get {
                return ((string)(this["DBSelectMemberTag"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM clanmembers WHERE status > 0")]
        public string DBSelectDonation {
            get {
                return ((string)(this["DBSelectDonation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AND send > 0 AND receive > 0")]
        public string DBSelectDonationRatio {
            get {
                return ((string)(this["DBSelectDonationRatio"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT sum(send) tsend, sum(receive) treceive FROM clanmembers WHERE 1 = 1")]
        public string DBSelectDonationTotal {
            get {
                return ((string)(this["DBSelectDonationTotal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ORDER BY trophies DESC")]
        public string DBSelectMemberListOrder {
            get {
                return ((string)(this["DBSelectMemberListOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ORDER BY send DESC LIMIT 5")]
        public string DBSelectDonationSendOrder {
            get {
                return ((string)(this["DBSelectDonationSendOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ORDER BY receive DESC LIMIT 5")]
        public string DBSelectDonationReceiveOrder {
            get {
                return ((string)(this["DBSelectDonationReceiveOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ORDER BY ratio DESC LIMIT 5")]
        public string DBSelectDonationRatioOrder {
            get {
                return ((string)(this["DBSelectDonationRatioOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT {0} FROM league WHERE id = {1}")]
        public string DBSelectLeaque {
            get {
                return ((string)(this["DBSelectLeaque"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api-assets.clashofclans.com")]
        public string CoCMediaURL {
            get {
                return ((string)(this["CoCMediaURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE ClanInfo SET warpub = 0 WHERE tag = \'{0}\'")]
        public string DBSysUpdateNotPublicWar {
            get {
                return ((string)(this["DBSysUpdateNotPublicWar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM ClanMember WHERE COCSEASON(year,season) = 1")]
        public string DBSysUpdateMembers {
            get {
                return ((string)(this["DBSysUpdateMembers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM ClanInfo")]
        public string DBSysUpdateClanInfo {
            get {
                return ((string)(this["DBSysUpdateClanInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM {0}")]
        public string DBSysUpdateSelect {
            get {
                return ((string)(this["DBSysUpdateSelect"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/{0}/{1}/{2}/{3}/{4}")]
        public string CoCLocalMediaURL {
            get {
                return ((string)(this["CoCLocalMediaURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM clanwar ORDER BY dtend DESC")]
        public string DBSelectWarClan {
            get {
                return ((string)(this["DBSelectWarClan"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LIMIT 3")]
        public string DBSelectWarLast {
            get {
                return ((string)(this["DBSelectWarLast"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/assets/html/ClanInfo.html")]
        public string NotifyRssClanLink {
            get {
                return ((string)(this["NotifyRssClanLink"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/assets/html/ClanList.html")]
        public string NotifyRssMemberLink {
            get {
                return ((string)(this["NotifyRssMemberLink"]));
            }
        }
    }
}
