//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.2034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stCoCClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemberNew {
            get {
                return ((bool)(this["MemberNew"]));
            }
            set {
                this["MemberNew"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemberExit {
            get {
                return ((bool)(this["MemberExit"]));
            }
            set {
                this["MemberExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemberChangeNik {
            get {
                return ((bool)(this["MemberChangeNik"]));
            }
            set {
                this["MemberChangeNik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemberChangeRole {
            get {
                return ((bool)(this["MemberChangeRole"]));
            }
            set {
                this["MemberChangeRole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemberChangeLevel {
            get {
                return ((bool)(this["MemberChangeLevel"]));
            }
            set {
                this["MemberChangeLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemberChangeLeague {
            get {
                return ((bool)(this["MemberChangeLeague"]));
            }
            set {
                this["MemberChangeLeague"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemberChangeTrophies {
            get {
                return ((bool)(this["MemberChangeTrophies"]));
            }
            set {
                this["MemberChangeTrophies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemberChangeDonationSend {
            get {
                return ((bool)(this["MemberChangeDonationSend"]));
            }
            set {
                this["MemberChangeDonationSend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MemberChangeDonationReceive {
            get {
                return ((bool)(this["MemberChangeDonationReceive"]));
            }
            set {
                this["MemberChangeDonationReceive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClanChangeName {
            get {
                return ((bool)(this["ClanChangeName"]));
            }
            set {
                this["ClanChangeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClanChangeType {
            get {
                return ((bool)(this["ClanChangeType"]));
            }
            set {
                this["ClanChangeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClanChangeLevel {
            get {
                return ((bool)(this["ClanChangeLevel"]));
            }
            set {
                this["ClanChangeLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClanChangePoints {
            get {
                return ((bool)(this["ClanChangePoints"]));
            }
            set {
                this["ClanChangePoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClanChangeMembers {
            get {
                return ((bool)(this["ClanChangeMembers"]));
            }
            set {
                this["ClanChangeMembers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClanChangeTrophies {
            get {
                return ((bool)(this["ClanChangeTrophies"]));
            }
            set {
                this["ClanChangeTrophies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClanChangeWarWin {
            get {
                return ((bool)(this["ClanChangeWarWin"]));
            }
            set {
                this["ClanChangeWarWin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClanChangeWarFrequency {
            get {
                return ((bool)(this["ClanChangeWarFrequency"]));
            }
            set {
                this["ClanChangeWarFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClanChangeWarSeries {
            get {
                return ((bool)(this["ClanChangeWarSeries"]));
            }
            set {
                this["ClanChangeWarSeries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClanChangeWarPublic {
            get {
                return ((bool)(this["ClanChangeWarPublic"]));
            }
            set {
                this["ClanChangeWarPublic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WarClanEnd {
            get {
                return ((bool)(this["WarClanEnd"]));
            }
            set {
                this["WarClanEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IRCServer {
            get {
                return ((string)(this["IRCServer"]));
            }
            set {
                this["IRCServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IRCPort {
            get {
                return ((string)(this["IRCPort"]));
            }
            set {
                this["IRCPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IRCChannel {
            get {
                return ((string)(this["IRCChannel"]));
            }
            set {
                this["IRCChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IRCNik {
            get {
                return ((string)(this["IRCNik"]));
            }
            set {
                this["IRCNik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IRCPassword {
            get {
                return ((string)(this["IRCPassword"]));
            }
            set {
                this["IRCPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IRCKickRespawn {
            get {
                return ((bool)(this["IRCKickRespawn"]));
            }
            set {
                this["IRCKickRespawn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IRCServerMessage {
            get {
                return ((bool)(this["IRCServerMessage"]));
            }
            set {
                this["IRCServerMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IRCNoticeMessage {
            get {
                return ((bool)(this["IRCNoticeMessage"]));
            }
            set {
                this["IRCNoticeMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRCPrivateMessage {
            get {
                return ((bool)(this["IRCPrivateMessage"]));
            }
            set {
                this["IRCPrivateMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USRCoCServer {
            get {
                return ((string)(this["USRCoCServer"]));
            }
            set {
                this["USRCoCServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USRCoCTag {
            get {
                return ((string)(this["USRCoCTag"]));
            }
            set {
                this["USRCoCTag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public long USRInformerId {
            get {
                return ((long)(this["USRInformerId"]));
            }
            set {
                this["USRInformerId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USRWikiHome {
            get {
                return ((string)(this["USRWikiHome"]));
            }
            set {
                this["USRWikiHome"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IRCLanguage {
            get {
                return ((string)(this["IRCLanguage"]));
            }
            set {
                this["IRCLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public long USRNotifyUpdateTime {
            get {
                return ((long)(this["USRNotifyUpdateTime"]));
            }
            set {
                this["USRNotifyUpdateTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring />\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection USRUrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["USRUrl"]));
            }
            set {
                this["USRUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string USRServerVersion {
            get {
                return ((string)(this["USRServerVersion"]));
            }
            set {
                this["USRServerVersion"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}assets/clientsetup.json?{1}")]
        public string URLServerSetup {
            get {
                return ((string)(this["URLServerSetup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}clan/player/{1}/")]
        public string URLUserSetup {
            get {
                return ((string)(this["URLUserSetup"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/json/?{2}")]
        public string URLNotifySetup {
            get {
                return ((string)(this["URLNotifySetup"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TSMIMultiselect {
            get {
                return ((bool)(this["TSMIMultiselect"]));
            }
            set {
                this["TSMIMultiselect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TSMIScroll {
            get {
                return ((bool)(this["TSMIScroll"]));
            }
            set {
                this["TSMIScroll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int USRTimerNotifyInterval {
            get {
                return ((int)(this["USRTimerNotifyInterval"]));
            }
            set {
                this["USRTimerNotifyInterval"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/list/?{2}")]
        public string URLMemberSetup {
            get {
                return ((string)(this["URLMemberSetup"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TSMINotifyGroup {
            get {
                return ((bool)(this["TSMINotifyGroup"]));
            }
            set {
                this["TSMINotifyGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<div style=\"overflow-x:auto;\"><table border=\"1\" cellspacing=\"1\" cellpadding=\"2\">")]
        public string ExportHtmlTableStart {
            get {
                return ((string)(this["ExportHtmlTableStart"]));
            }
            set {
                this["ExportHtmlTableStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<tr><th colspan=\"{0}\" align=\"{1}\" bgcolor=\"{2}\">{3}</th></tr>")]
        public string ExportHtmlTableTh {
            get {
                return ((string)(this["ExportHtmlTableTh"]));
            }
            set {
                this["ExportHtmlTableTh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("</table></div>")]
        public string ExportHtmlTableEnd {
            get {
                return ((string)(this["ExportHtmlTableEnd"]));
            }
            set {
                this["ExportHtmlTableEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<th bgcolor=\"{0}\" width=\"{1}\" align=\"{2}\">{3}</th>")]
        public string ExportHtmlTableColumnFormat {
            get {
                return ((string)(this["ExportHtmlTableColumnFormat"]));
            }
            set {
                this["ExportHtmlTableColumnFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<{0}tr>")]
        public string ExportHtmlTableTr {
            get {
                return ((string)(this["ExportHtmlTableTr"]));
            }
            set {
                this["ExportHtmlTableTr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td align=\"{0}\">{1}</td>")]
        public string ExportHtmlTableTd {
            get {
                return ((string)(this["ExportHtmlTableTd"]));
            }
            set {
                this["ExportHtmlTableTd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<style>\r\ntable { border-collapse: collapse; width: 900%;}\r\nth, td { border-bottom" +
            ": 1px solid #ddd; }\r\ntr:hover { background-color: #f5f5f5; }\r\nth { background-co" +
            "lor: #4CAF50; color: white; }\r\n</style>\r\n")]
        public string ExportHtmlTableStyle {
            get {
                return ((string)(this["ExportHtmlTableStyle"]));
            }
            set {
                this["ExportHtmlTableStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExportPath {
            get {
                return ((string)(this["ExportPath"]));
            }
            set {
                this["ExportPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DADADA")]
        public string ExportHtmlTableGroupColor {
            get {
                return ((string)(this["ExportHtmlTableGroupColor"]));
            }
            set {
                this["ExportHtmlTableGroupColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#C0C0C0")]
        public string ExportHtmlTableColumnColor {
            get {
                return ((string)(this["ExportHtmlTableColumnColor"]));
            }
            set {
                this["ExportHtmlTableColumnColor"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<.*?>|&nbsp;|&zwnj;|&raquo;|&laquo;")]
        public string ChatFilterHtml {
            get {
                return ((string)(this["ChatFilterHtml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}/{1}/{2}/")]
        public string URLIrcArchive {
            get {
                return ((string)(this["URLIrcArchive"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int IRCChatHistory {
            get {
                return ((int)(this["IRCChatHistory"]));
            }
            set {
                this["IRCChatHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRCChatEmojiEnabled {
            get {
                return ((bool)(this["IRCChatEmojiEnabled"]));
            }
            set {
                this["IRCChatEmojiEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IRCChatBBCodeEnabled {
            get {
                return ((bool)(this["IRCChatBBCodeEnabled"]));
            }
            set {
                this["IRCChatBBCodeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("trnsl.1.1.20170205T092429Z.d94b9696b7a04814.a73de092de64950b3295feb05de2b0dfb9f82" +
            "29e")]
        public string YandexServiceKeyTranslation {
            get {
                return ((string)(this["YandexServiceKeyTranslation"]));
            }
            set {
                this["YandexServiceKeyTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pdct.1.1.20170205T092623Z.f0c083fed983e67d.1ac4e3f996d2a66f6dbbf28f0fd08234e3b216" +
            "21")]
        public string YandexServiceKeyPredictate {
            get {
                return ((string)(this["YandexServiceKeyPredictate"]));
            }
            set {
                this["YandexServiceKeyPredictate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0}{1}/player/{2}/{3}/?{4}")]
        public string URLServerInformer {
            get {
                return ((string)(this["URLServerInformer"]));
            }
            set {
                this["URLServerInformer"] = value;
            }
        }
    }
}
