//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.2034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stIrcManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("stIrcManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage IRC channel utility for stCoCServer engine.
        /// </summary>
        internal static string banRun {
            get {
                return ResourceManager.GetString("banRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ini file Error Load: {0}.
        /// </summary>
        internal static string fmtIniErrorLoad {
            get {
                return ResourceManager.GetString("fmtIniErrorLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ini file Not Found: {0}.
        /// </summary>
        internal static string fmtIniNotFound {
            get {
                return ResourceManager.GetString("fmtIniNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ChanServ FLAGS {0} {1}!*@{2} -V+oO.
        /// </summary>
        internal static string fmtIRCAdmin {
            get {
                return ResourceManager.GetString("fmtIRCAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MODE {0} +b $r:{1}!*@{2}.
        /// </summary>
        internal static string fmtIRCBan {
            get {
                return ResourceManager.GetString("fmtIRCBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KICK {0} {1}.
        /// </summary>
        internal static string fmtIRCKick {
            get {
                return ResourceManager.GetString("fmtIRCKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (stage{0}) - Type you Bot IRC password: .
        /// </summary>
        internal static string fmtIRCPassword {
            get {
                return ResourceManager.GetString("fmtIRCPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NickServ REGISTER {0} {1}.
        /// </summary>
        internal static string fmtIRCRegBot {
            get {
                return ResourceManager.GetString("fmtIRCRegBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ChanServ REGISTER {0} &quot;Clash of Clans {1}&quot;.
        /// </summary>
        internal static string fmtIRCRegChannel {
            get {
                return ResourceManager.GetString("fmtIRCRegChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ChanServ SET {0} {1}.
        /// </summary>
        internal static string fmtIRCSet2Channel {
            get {
                return ResourceManager.GetString("fmtIRCSet2Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ChanServ SET {0} {1} {2}.
        /// </summary>
        internal static string fmtIRCSet3Channel {
            get {
                return ResourceManager.GetString("fmtIRCSet3Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ChanServ SET {0} {1} {2} {3}.
        /// </summary>
        internal static string fmtIRCSet4Channel {
            get {
                return ResourceManager.GetString("fmtIRCSet4Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TOPIC {0} :&quot;{1}&quot;.
        /// </summary>
        internal static string fmtIRCTopic {
            get {
                return ResourceManager.GetString("fmtIRCTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not action found: {0}.
        /// </summary>
        internal static string fmtOptionNotAction {
            get {
                return ResourceManager.GetString("fmtOptionNotAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention! Add or Edit line in configuration file stCoCServer.ini: {1}IRCPassword={0}{1}- and restart server!.
        /// </summary>
        internal static string fmtPasswordAddOrChange {
            get {
                return ResourceManager.GetString("fmtPasswordAddOrChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ERROR.
        /// </summary>
        internal static string PrnError {
            get {
                return ResourceManager.GetString("PrnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        internal static string PrnOk {
            get {
                return ResourceManager.GetString("PrnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batch mode Not support this operations.
        /// </summary>
        internal static string txtBatchModeNotSupport {
            get {
                return ResourceManager.GetString("txtBatchModeNotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set user nickname to admin privilege.
        /// </summary>
        internal static string txtHelpActionAdmin {
            get {
                return ResourceManager.GetString("txtHelpActionAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ban  user nickname.
        /// </summary>
        internal static string txtHelpActionBan {
            get {
                return ResourceManager.GetString("txtHelpActionBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set channel Message, Description and URL.
        /// </summary>
        internal static string txtHelpActionChannel {
            get {
                return ResourceManager.GetString("txtHelpActionChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kick user nickname.
        /// </summary>
        internal static string txtHelpActionKick {
            get {
                return ResourceManager.GetString("txtHelpActionKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration Bot nickname from IRC server.
        /// </summary>
        internal static string txtHelpActionRegbot {
            get {
                return ResourceManager.GetString("txtHelpActionRegbot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Registration channel to Bot nickname.
        /// </summary>
        internal static string txtHelpActionRegchan {
            get {
                return ResourceManager.GetString("txtHelpActionRegchan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set channel Topic.
        /// </summary>
        internal static string txtHelpActionTopic {
            get {
                return ResourceManager.GetString("txtHelpActionTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Batch mode, no interactive.
        /// </summary>
        internal static string txtHelpBatch {
            get {
                return ResourceManager.GetString("txtHelpBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IRC Bot nickname.
        /// </summary>
        internal static string txtHelpBotname {
            get {
                return ResourceManager.GetString("txtHelpBotname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IRC channel include &apos;#&apos;.
        /// </summary>
        internal static string txtHelpChannel {
            get {
                return ResourceManager.GetString("txtHelpChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan Name.
        /// </summary>
        internal static string txtHelpClaname {
            get {
                return ResourceManager.GetString("txtHelpClaname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan ID.
        /// </summary>
        internal static string txtHelpClanid {
            get {
                return ResourceManager.GetString("txtHelpClanid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email for registration respond.
        /// </summary>
        internal static string txtHelpEmail {
            get {
                return ResourceManager.GetString("txtHelpEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на user/bot nickname IP allow for admin privilege.
        /// </summary>
        internal static string txtHelpIpAllow {
            get {
                return ResourceManager.GetString("txtHelpIpAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show configuration and exit.
        /// </summary>
        internal static string txtHelpShowConfig {
            get {
                return ResourceManager.GetString("txtHelpShowConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IRC channel Topic.
        /// </summary>
        internal static string txtHelpTopic {
            get {
                return ResourceManager.GetString("txtHelpTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User nickname.
        /// </summary>
        internal static string txtHelpUsrname {
            get {
                return ResourceManager.GetString("txtHelpUsrname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web home page (URL).
        /// </summary>
        internal static string txtHelpWeb {
            get {
                return ResourceManager.GetString("txtHelpWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not IRC Bot nickname.
        /// </summary>
        internal static string txtOptionNotBotName {
            get {
                return ResourceManager.GetString("txtOptionNotBotName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not Clan Id.
        /// </summary>
        internal static string txtOptionNotClanId {
            get {
                return ResourceManager.GetString("txtOptionNotClanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not Clan Name.
        /// </summary>
        internal static string txtOptionNotClanName {
            get {
                return ResourceManager.GetString("txtOptionNotClanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not Home Url.
        /// </summary>
        internal static string txtOptionNotHomeUrl {
            get {
                return ResourceManager.GetString("txtOptionNotHomeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not IRC Channel.
        /// </summary>
        internal static string txtOptionNotIrcChannel {
            get {
                return ResourceManager.GetString("txtOptionNotIrcChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not Topic to IRC Channel.
        /// </summary>
        internal static string txtOptionNotIrcTopic {
            get {
                return ResourceManager.GetString("txtOptionNotIrcTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not user IRC nickname.
        /// </summary>
        internal static string txtOptionNotNickName {
            get {
                return ResourceManager.GetString("txtOptionNotNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not registred Email adress.
        /// </summary>
        internal static string txtOptionNotRegEmail {
            get {
                return ResourceManager.GetString("txtOptionNotRegEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на not valid Email adress.
        /// </summary>
        internal static string txtOptionNotValidEmail {
            get {
                return ResourceManager.GetString("txtOptionNotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password phase is empty.
        /// </summary>
        internal static string txtOptionPasswordEmpty {
            get {
                return ResourceManager.GetString("txtOptionPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stage 1/2: input password Not equals!.
        /// </summary>
        internal static string txtPasswordNotEquals {
            get {
                return ResourceManager.GetString("txtPasswordNotEquals", resourceCulture);
            }
        }
    }
}
