//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.2034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceNotify {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceNotify() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("stClient.Properties.ResourceNotify", typeof(ResourceNotify).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fm2ClanChangeMembers {
            get {
                return ResourceManager.GetString("fm2ClanChangeMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan change Level: {5}.
        /// </summary>
        public static string fmt1ClanChangeLevel {
            get {
                return ResourceManager.GetString("fmt1ClanChangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan change Members: {5}.
        /// </summary>
        public static string fmt1ClanChangeMembers {
            get {
                return ResourceManager.GetString("fmt1ClanChangeMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan change Name: to {2}.
        /// </summary>
        public static string fmt1ClanChangeName {
            get {
                return ResourceManager.GetString("fmt1ClanChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan change Points: {5}.
        /// </summary>
        public static string fmt1ClanChangePoints {
            get {
                return ResourceManager.GetString("fmt1ClanChangePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan change Trophies: {5}.
        /// </summary>
        public static string fmt1ClanChangeTrophies {
            get {
                return ResourceManager.GetString("fmt1ClanChangeTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan change Type: {2}.
        /// </summary>
        public static string fmt1ClanChangeType {
            get {
                return ResourceManager.GetString("fmt1ClanChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan change war Frequency: {2}.
        /// </summary>
        public static string fmt1ClanChangeWarFrequency {
            get {
                return ResourceManager.GetString("fmt1ClanChangeWarFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan change war Public: {2}.
        /// </summary>
        public static string fmt1ClanChangeWarPublic {
            get {
                return ResourceManager.GetString("fmt1ClanChangeWarPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan change war Series: {5}.
        /// </summary>
        public static string fmt1ClanChangeWarSeries {
            get {
                return ResourceManager.GetString("fmt1ClanChangeWarSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan change war Win: {5}.
        /// </summary>
        public static string fmt1ClanChangeWarWin {
            get {
                return ResourceManager.GetString("fmt1ClanChangeWarWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} change Donation receive: {5}.
        /// </summary>
        public static string fmt1MemberChangeDonationReceive {
            get {
                return ResourceManager.GetString("fmt1MemberChangeDonationReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} change Donation send: {5}.
        /// </summary>
        public static string fmt1MemberChangeDonationSend {
            get {
                return ResourceManager.GetString("fmt1MemberChangeDonationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} change League:  {2}.
        /// </summary>
        public static string fmt1MemberChangeLeague {
            get {
                return ResourceManager.GetString("fmt1MemberChangeLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} change Level: {5}.
        /// </summary>
        public static string fmt1MemberChangeLevel {
            get {
                return ResourceManager.GetString("fmt1MemberChangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} change Nik: to {2}.
        /// </summary>
        public static string fmt1MemberChangeNik {
            get {
                return ResourceManager.GetString("fmt1MemberChangeNik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} change Role: {2}.
        /// </summary>
        public static string fmt1MemberChangeRole {
            get {
                return ResourceManager.GetString("fmt1MemberChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} change Trophies: {5}.
        /// </summary>
        public static string fmt1MemberChangeTrophies {
            get {
                return ResourceManager.GetString("fmt1MemberChangeTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} left from clan.
        /// </summary>
        public static string fmt1MemberExit {
            get {
                return ResourceManager.GetString("fmt1MemberExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New member: {0}.
        /// </summary>
        public static string fmt1MemberNew {
            get {
                return ResourceManager.GetString("fmt1MemberNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clan War {0} ended.
        /// </summary>
        public static string fmt1WarClanEnd {
            get {
                return ResourceManager.GetString("fmt1WarClanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2ClanChangeLevel {
            get {
                return ResourceManager.GetString("fmt2ClanChangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2ClanChangeMembers {
            get {
                return ResourceManager.GetString("fmt2ClanChangeMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}.
        /// </summary>
        public static string fmt2ClanChangeName {
            get {
                return ResourceManager.GetString("fmt2ClanChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2ClanChangePoints {
            get {
                return ResourceManager.GetString("fmt2ClanChangePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2ClanChangeTrophies {
            get {
                return ResourceManager.GetString("fmt2ClanChangeTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2ClanChangeType {
            get {
                return ResourceManager.GetString("fmt2ClanChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2ClanChangeWarFrequency {
            get {
                return ResourceManager.GetString("fmt2ClanChangeWarFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2ClanChangeWarPublic {
            get {
                return ResourceManager.GetString("fmt2ClanChangeWarPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2ClanChangeWarSeries {
            get {
                return ResourceManager.GetString("fmt2ClanChangeWarSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2ClanChangeWarWin {
            get {
                return ResourceManager.GetString("fmt2ClanChangeWarWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2MemberChangeDonationReceive {
            get {
                return ResourceManager.GetString("fmt2MemberChangeDonationReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2MemberChangeDonationSend {
            get {
                return ResourceManager.GetString("fmt2MemberChangeDonationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2MemberChangeLeague {
            get {
                return ResourceManager.GetString("fmt2MemberChangeLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2MemberChangeLevel {
            get {
                return ResourceManager.GetString("fmt2MemberChangeLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {6}.
        /// </summary>
        public static string fmt2MemberChangeNik {
            get {
                return ResourceManager.GetString("fmt2MemberChangeNik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2MemberChangeRole {
            get {
                return ResourceManager.GetString("fmt2MemberChangeRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2}.
        /// </summary>
        public static string fmt2MemberChangeTrophies {
            get {
                return ResourceManager.GetString("fmt2MemberChangeTrophies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {6}.
        /// </summary>
        public static string fmt2MemberExit {
            get {
                return ResourceManager.GetString("fmt2MemberExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {6}.
        /// </summary>
        public static string fmt2MemberNew {
            get {
                return ResourceManager.GetString("fmt2MemberNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {1} -&gt; {2} {3} {4}.
        /// </summary>
        public static string fmt2WarClanEnd {
            get {
                return ResourceManager.GetString("fmt2WarClanEnd", resourceCulture);
            }
        }
    }
}
