//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.2034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("stUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap MboxAllow {
            get {
                object obj = ResourceManager.GetObject("MboxAllow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access Allow.
        /// </summary>
        public static string MboxAllowStr {
            get {
                return ResourceManager.GetString("MboxAllowStr", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap MboxDefault {
            get {
                object obj = ResourceManager.GetObject("MboxDefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на undefined error.
        /// </summary>
        public static string MboxDefaultMsg {
            get {
                return ResourceManager.GetString("MboxDefaultMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string MboxDefaultStr {
            get {
                return ResourceManager.GetString("MboxDefaultStr", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap MboxDeny {
            get {
                object obj = ResourceManager.GetObject("MboxDeny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Access Deny.
        /// </summary>
        public static string MboxDenyStr {
            get {
                return ResourceManager.GetString("MboxDenyStr", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap MboxError {
            get {
                object obj = ResourceManager.GetObject("MboxError", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string MboxErrorStr {
            get {
                return ResourceManager.GetString("MboxErrorStr", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap MboxInfo {
            get {
                object obj = ResourceManager.GetObject("MboxInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string MboxInfoStr {
            get {
                return ResourceManager.GetString("MboxInfoStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на stMessageBox instance is null.
        /// </summary>
        public static string MboxIsNull {
            get {
                return ResourceManager.GetString("MboxIsNull", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap PanelTogle {
            get {
                object obj = ResourceManager.GetObject("PanelTogle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на process run, not change active control.
        /// </summary>
        public static string UIExceptionBusy {
            get {
                return ResourceManager.GetString("UIExceptionBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на control library stUI: {0}.
        /// </summary>
        public static string UIExceptionHead {
            get {
                return ResourceManager.GetString("UIExceptionHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на control stMessageBox can not determine its parent.
        /// </summary>
        public static string UIExceptionParentIsNull {
            get {
                return ResourceManager.GetString("UIExceptionParentIsNull", resourceCulture);
            }
        }
    }
}
