

using System;
using System.Collections.Generic;

namespace stGeo
{
    public static partial class MaxMindUtil
    {
        private static readonly List<stGeoCountry> geoCountrys = new List<stGeoCountry>()
        {
			new stGeoCountry() { Id = 0,  Tag = "--", Name = "N/A" },
			new stGeoCountry() { Id = 1,  Tag = "AP", Name = "Asia/Pacific Region" },
			new stGeoCountry() { Id = 2,  Tag = "EU", Name = "Europe" },
			new stGeoCountry() { Id = 3,  Tag = "AD", Name = "Andorra" },
			new stGeoCountry() { Id = 4,  Tag = "AE", Name = "United Arab Emirates" },
			new stGeoCountry() { Id = 5,  Tag = "AF", Name = "Afghanistan" },
			new stGeoCountry() { Id = 6,  Tag = "AG", Name = "Antigua and Barbuda" },
			new stGeoCountry() { Id = 7,  Tag = "AI", Name = "Anguilla" },
			new stGeoCountry() { Id = 8,  Tag = "AL", Name = "Albania" },
			new stGeoCountry() { Id = 9,  Tag = "AM", Name = "Armenia" },
			new stGeoCountry() { Id = 10,  Tag = "CW", Name = "Curacao" },
			new stGeoCountry() { Id = 11,  Tag = "AO", Name = "Angola" },
			new stGeoCountry() { Id = 12,  Tag = "AQ", Name = "Antarctica" },
			new stGeoCountry() { Id = 13,  Tag = "AR", Name = "Argentina" },
			new stGeoCountry() { Id = 14,  Tag = "AS", Name = "American Samoa" },
			new stGeoCountry() { Id = 15,  Tag = "AT", Name = "Austria" },
			new stGeoCountry() { Id = 16,  Tag = "AU", Name = "Australia" },
			new stGeoCountry() { Id = 17,  Tag = "AW", Name = "Aruba" },
			new stGeoCountry() { Id = 18,  Tag = "AZ", Name = "Azerbaijan" },
			new stGeoCountry() { Id = 19,  Tag = "BA", Name = "Bosnia and Herzegovina" },
			new stGeoCountry() { Id = 20,  Tag = "BB", Name = "Barbados" },
			new stGeoCountry() { Id = 21,  Tag = "BD", Name = "Bangladesh" },
			new stGeoCountry() { Id = 22,  Tag = "BE", Name = "Belgium" },
			new stGeoCountry() { Id = 23,  Tag = "BF", Name = "Burkina Faso" },
			new stGeoCountry() { Id = 24,  Tag = "BG", Name = "Bulgaria" },
			new stGeoCountry() { Id = 25,  Tag = "BH", Name = "Bahrain" },
			new stGeoCountry() { Id = 26,  Tag = "BI", Name = "Burundi" },
			new stGeoCountry() { Id = 27,  Tag = "BJ", Name = "Benin" },
			new stGeoCountry() { Id = 28,  Tag = "BM", Name = "Bermuda" },
			new stGeoCountry() { Id = 29,  Tag = "BN", Name = "Brunei Darussalam" },
			new stGeoCountry() { Id = 30,  Tag = "BO", Name = "Bolivia" },
			new stGeoCountry() { Id = 31,  Tag = "BR", Name = "Brazil" },
			new stGeoCountry() { Id = 32,  Tag = "BS", Name = "Bahamas" },
			new stGeoCountry() { Id = 33,  Tag = "BT", Name = "Bhutan" },
			new stGeoCountry() { Id = 34,  Tag = "BV", Name = "Bouvet Island" },
			new stGeoCountry() { Id = 35,  Tag = "BW", Name = "Botswana" },
			new stGeoCountry() { Id = 36,  Tag = "BY", Name = "Belarus" },
			new stGeoCountry() { Id = 37,  Tag = "BZ", Name = "Belize" },
			new stGeoCountry() { Id = 38,  Tag = "CA", Name = "Canada" },
			new stGeoCountry() { Id = 39,  Tag = "CC", Name = "Cocos (Keeling) Islands" },
			new stGeoCountry() { Id = 40,  Tag = "CD", Name = "Congo, The Democratic Republic of the" },
			new stGeoCountry() { Id = 41,  Tag = "CF", Name = "Central African Republic" },
			new stGeoCountry() { Id = 42,  Tag = "CG", Name = "Congo" },
			new stGeoCountry() { Id = 43,  Tag = "CH", Name = "Switzerland" },
			new stGeoCountry() { Id = 44,  Tag = "CI", Name = "Cote D'Ivoire" },
			new stGeoCountry() { Id = 45,  Tag = "CK", Name = "Cook Islands" },
			new stGeoCountry() { Id = 46,  Tag = "CL", Name = "Chile" },
			new stGeoCountry() { Id = 47,  Tag = "CM", Name = "Cameroon" },
			new stGeoCountry() { Id = 48,  Tag = "CN", Name = "China" },
			new stGeoCountry() { Id = 49,  Tag = "CO", Name = "Colombia" },
			new stGeoCountry() { Id = 50,  Tag = "CR", Name = "Costa Rica" },
			new stGeoCountry() { Id = 51,  Tag = "CU", Name = "Cuba" },
			new stGeoCountry() { Id = 52,  Tag = "CV", Name = "Cape Verde" },
			new stGeoCountry() { Id = 53,  Tag = "CX", Name = "Christmas Island" },
			new stGeoCountry() { Id = 54,  Tag = "CY", Name = "Cyprus" },
			new stGeoCountry() { Id = 55,  Tag = "CZ", Name = "Czech Republic" },
			new stGeoCountry() { Id = 56,  Tag = "DE", Name = "Germany" },
			new stGeoCountry() { Id = 57,  Tag = "DJ", Name = "Djibouti" },
			new stGeoCountry() { Id = 58,  Tag = "DK", Name = "Denmark" },
			new stGeoCountry() { Id = 59,  Tag = "DM", Name = "Dominica" },
			new stGeoCountry() { Id = 60,  Tag = "DO", Name = "Dominican Republic" },
			new stGeoCountry() { Id = 61,  Tag = "DZ", Name = "Algeria" },
			new stGeoCountry() { Id = 62,  Tag = "EC", Name = "Ecuador" },
			new stGeoCountry() { Id = 63,  Tag = "EE", Name = "Estonia" },
			new stGeoCountry() { Id = 64,  Tag = "EG", Name = "Egypt" },
			new stGeoCountry() { Id = 65,  Tag = "EH", Name = "Western Sahara" },
			new stGeoCountry() { Id = 66,  Tag = "ER", Name = "Eritrea" },
			new stGeoCountry() { Id = 67,  Tag = "ES", Name = "Spain" },
			new stGeoCountry() { Id = 68,  Tag = "ET", Name = "Ethiopia" },
			new stGeoCountry() { Id = 69,  Tag = "FI", Name = "Finland" },
			new stGeoCountry() { Id = 70,  Tag = "FJ", Name = "Fiji" },
			new stGeoCountry() { Id = 71,  Tag = "FK", Name = "Falkland Islands (Malvinas)" },
			new stGeoCountry() { Id = 72,  Tag = "FM", Name = "Micronesia, Federated States of" },
			new stGeoCountry() { Id = 73,  Tag = "FO", Name = "Faroe Islands" },
			new stGeoCountry() { Id = 74,  Tag = "FR", Name = "France" },
			new stGeoCountry() { Id = 75,  Tag = "SX", Name = "Sint Maarten (Dutch part)" },
			new stGeoCountry() { Id = 76,  Tag = "GA", Name = "Gabon" },
			new stGeoCountry() { Id = 77,  Tag = "GB", Name = "United Kingdom" },
			new stGeoCountry() { Id = 78,  Tag = "GD", Name = "Grenada" },
			new stGeoCountry() { Id = 79,  Tag = "GE", Name = "Georgia" },
			new stGeoCountry() { Id = 80,  Tag = "GF", Name = "French Guiana" },
			new stGeoCountry() { Id = 81,  Tag = "GH", Name = "Ghana" },
			new stGeoCountry() { Id = 82,  Tag = "GI", Name = "Gibraltar" },
			new stGeoCountry() { Id = 83,  Tag = "GL", Name = "Greenland" },
			new stGeoCountry() { Id = 84,  Tag = "GM", Name = "Gambia" },
			new stGeoCountry() { Id = 85,  Tag = "GN", Name = "Guinea" },
			new stGeoCountry() { Id = 86,  Tag = "GP", Name = "Guadeloupe" },
			new stGeoCountry() { Id = 87,  Tag = "GQ", Name = "Equatorial Guinea" },
			new stGeoCountry() { Id = 88,  Tag = "GR", Name = "Greece" },
			new stGeoCountry() { Id = 89,  Tag = "GS", Name = "South Georgia and the South Sandwich Islands" },
			new stGeoCountry() { Id = 90,  Tag = "GT", Name = "Guatemala" },
			new stGeoCountry() { Id = 91,  Tag = "GU", Name = "Guam" },
			new stGeoCountry() { Id = 92,  Tag = "GW", Name = "Guinea-Bissau" },
			new stGeoCountry() { Id = 93,  Tag = "GY", Name = "Guyana" },
			new stGeoCountry() { Id = 94,  Tag = "HK", Name = "Hong Kong" },
			new stGeoCountry() { Id = 95,  Tag = "HM", Name = "Heard Island and McDonald Islands" },
			new stGeoCountry() { Id = 96,  Tag = "HN", Name = "Honduras" },
			new stGeoCountry() { Id = 97,  Tag = "HR", Name = "Croatia" },
			new stGeoCountry() { Id = 98,  Tag = "HT", Name = "Haiti" },
			new stGeoCountry() { Id = 99,  Tag = "HU", Name = "Hungary" },
			new stGeoCountry() { Id = 100,  Tag = "ID", Name = "Indonesia" },
			new stGeoCountry() { Id = 101,  Tag = "IE", Name = "Ireland" },
			new stGeoCountry() { Id = 102,  Tag = "IL", Name = "Israel" },
			new stGeoCountry() { Id = 103,  Tag = "IN", Name = "India" },
			new stGeoCountry() { Id = 104,  Tag = "IO", Name = "British Indian Ocean Territory" },
			new stGeoCountry() { Id = 105,  Tag = "IQ", Name = "Iraq" },
			new stGeoCountry() { Id = 106,  Tag = "IR", Name = "Iran, Islamic Republic of" },
			new stGeoCountry() { Id = 107,  Tag = "IS", Name = "Iceland" },
			new stGeoCountry() { Id = 108,  Tag = "IT", Name = "Italy" },
			new stGeoCountry() { Id = 109,  Tag = "JM", Name = "Jamaica" },
			new stGeoCountry() { Id = 110,  Tag = "JO", Name = "Jordan" },
			new stGeoCountry() { Id = 111,  Tag = "JP", Name = "Japan" },
			new stGeoCountry() { Id = 112,  Tag = "KE", Name = "Kenya" },
			new stGeoCountry() { Id = 113,  Tag = "KG", Name = "Kyrgyzstan" },
			new stGeoCountry() { Id = 114,  Tag = "KH", Name = "Cambodia" },
			new stGeoCountry() { Id = 115,  Tag = "KI", Name = "Kiribati" },
			new stGeoCountry() { Id = 116,  Tag = "KM", Name = "Comoros" },
			new stGeoCountry() { Id = 117,  Tag = "KN", Name = "Saint Kitts and Nevis" },
			new stGeoCountry() { Id = 118,  Tag = "KP", Name = "Korea, Democratic People's Republic of" },
			new stGeoCountry() { Id = 119,  Tag = "KR", Name = "Korea, Republic of" },
			new stGeoCountry() { Id = 120,  Tag = "KW", Name = "Kuwait" },
			new stGeoCountry() { Id = 121,  Tag = "KY", Name = "Cayman Islands" },
			new stGeoCountry() { Id = 122,  Tag = "KZ", Name = "Kazakhstan" },
			new stGeoCountry() { Id = 123,  Tag = "LA", Name = "Lao People's Democratic Republic" },
			new stGeoCountry() { Id = 124,  Tag = "LB", Name = "Lebanon" },
			new stGeoCountry() { Id = 125,  Tag = "LC", Name = "Saint Lucia" },
			new stGeoCountry() { Id = 126,  Tag = "LI", Name = "Liechtenstein" },
			new stGeoCountry() { Id = 127,  Tag = "LK", Name = "Sri Lanka" },
			new stGeoCountry() { Id = 128,  Tag = "LR", Name = "Liberia" },
			new stGeoCountry() { Id = 129,  Tag = "LS", Name = "Lesotho" },
			new stGeoCountry() { Id = 130,  Tag = "LT", Name = "Lithuania" },
			new stGeoCountry() { Id = 131,  Tag = "LU", Name = "Luxembourg" },
			new stGeoCountry() { Id = 132,  Tag = "LV", Name = "Latvia" },
			new stGeoCountry() { Id = 133,  Tag = "LY", Name = "Libya" },
			new stGeoCountry() { Id = 134,  Tag = "MA", Name = "Morocco" },
			new stGeoCountry() { Id = 135,  Tag = "MC", Name = "Monaco" },
			new stGeoCountry() { Id = 136,  Tag = "MD", Name = "Moldova, Republic of" },
			new stGeoCountry() { Id = 137,  Tag = "MG", Name = "Madagascar" },
			new stGeoCountry() { Id = 138,  Tag = "MH", Name = "Marshall Islands" },
			new stGeoCountry() { Id = 139,  Tag = "MK", Name = "Macedonia" },
			new stGeoCountry() { Id = 140,  Tag = "ML", Name = "Mali" },
			new stGeoCountry() { Id = 141,  Tag = "MM", Name = "Myanmar" },
			new stGeoCountry() { Id = 142,  Tag = "MN", Name = "Mongolia" },
			new stGeoCountry() { Id = 143,  Tag = "MO", Name = "Macau" },
			new stGeoCountry() { Id = 144,  Tag = "MP", Name = "Northern Mariana Islands" },
			new stGeoCountry() { Id = 145,  Tag = "MQ", Name = "Martinique" },
			new stGeoCountry() { Id = 146,  Tag = "MR", Name = "Mauritania" },
			new stGeoCountry() { Id = 147,  Tag = "MS", Name = "Montserrat" },
			new stGeoCountry() { Id = 148,  Tag = "MT", Name = "Malta" },
			new stGeoCountry() { Id = 149,  Tag = "MU", Name = "Mauritius" },
			new stGeoCountry() { Id = 150,  Tag = "MV", Name = "Maldives" },
			new stGeoCountry() { Id = 151,  Tag = "MW", Name = "Malawi" },
			new stGeoCountry() { Id = 152,  Tag = "MX", Name = "Mexico" },
			new stGeoCountry() { Id = 153,  Tag = "MY", Name = "Malaysia" },
			new stGeoCountry() { Id = 154,  Tag = "MZ", Name = "Mozambique" },
			new stGeoCountry() { Id = 155,  Tag = "NA", Name = "Namibia" },
			new stGeoCountry() { Id = 156,  Tag = "NC", Name = "New Caledonia" },
			new stGeoCountry() { Id = 157,  Tag = "NE", Name = "Niger" },
			new stGeoCountry() { Id = 158,  Tag = "NF", Name = "Norfolk Island" },
			new stGeoCountry() { Id = 159,  Tag = "NG", Name = "Nigeria" },
			new stGeoCountry() { Id = 160,  Tag = "NI", Name = "Nicaragua" },
			new stGeoCountry() { Id = 161,  Tag = "NL", Name = "Netherlands" },
			new stGeoCountry() { Id = 162,  Tag = "NO", Name = "Norway" },
			new stGeoCountry() { Id = 163,  Tag = "NP", Name = "Nepal" },
			new stGeoCountry() { Id = 164,  Tag = "NR", Name = "Nauru" },
			new stGeoCountry() { Id = 165,  Tag = "NU", Name = "Niue" },
			new stGeoCountry() { Id = 166,  Tag = "NZ", Name = "New Zealand" },
			new stGeoCountry() { Id = 167,  Tag = "OM", Name = "Oman" },
			new stGeoCountry() { Id = 168,  Tag = "PA", Name = "Panama" },
			new stGeoCountry() { Id = 169,  Tag = "PE", Name = "Peru" },
			new stGeoCountry() { Id = 170,  Tag = "PF", Name = "French Polynesia" },
			new stGeoCountry() { Id = 171,  Tag = "PG", Name = "Papua New Guinea" },
			new stGeoCountry() { Id = 172,  Tag = "PH", Name = "Philippines" },
			new stGeoCountry() { Id = 173,  Tag = "PK", Name = "Pakistan" },
			new stGeoCountry() { Id = 174,  Tag = "PL", Name = "Poland" },
			new stGeoCountry() { Id = 175,  Tag = "PM", Name = "Saint Pierre and Miquelon" },
			new stGeoCountry() { Id = 176,  Tag = "PN", Name = "Pitcairn Islands" },
			new stGeoCountry() { Id = 177,  Tag = "PR", Name = "Puerto Rico" },
			new stGeoCountry() { Id = 178,  Tag = "PS", Name = "Palestinian Territory" },
			new stGeoCountry() { Id = 179,  Tag = "PT", Name = "Portugal" },
			new stGeoCountry() { Id = 180,  Tag = "PW", Name = "Palau" },
			new stGeoCountry() { Id = 181,  Tag = "PY", Name = "Paraguay" },
			new stGeoCountry() { Id = 182,  Tag = "QA", Name = "Qatar" },
			new stGeoCountry() { Id = 183,  Tag = "RE", Name = "Reunion" },
			new stGeoCountry() { Id = 184,  Tag = "RO", Name = "Romania" },
			new stGeoCountry() { Id = 185,  Tag = "RU", Name = "Russian Federation" },
			new stGeoCountry() { Id = 186,  Tag = "RW", Name = "Rwanda" },
			new stGeoCountry() { Id = 187,  Tag = "SA", Name = "Saudi Arabia" },
			new stGeoCountry() { Id = 188,  Tag = "SB", Name = "Solomon Islands" },
			new stGeoCountry() { Id = 189,  Tag = "SC", Name = "Seychelles" },
			new stGeoCountry() { Id = 190,  Tag = "SD", Name = "Sudan" },
			new stGeoCountry() { Id = 191,  Tag = "SE", Name = "Sweden" },
			new stGeoCountry() { Id = 192,  Tag = "SG", Name = "Singapore" },
			new stGeoCountry() { Id = 193,  Tag = "SH", Name = "Saint Helena" },
			new stGeoCountry() { Id = 194,  Tag = "SI", Name = "Slovenia" },
			new stGeoCountry() { Id = 195,  Tag = "SJ", Name = "Svalbard and Jan Mayen" },
			new stGeoCountry() { Id = 196,  Tag = "SK", Name = "Slovakia" },
			new stGeoCountry() { Id = 197,  Tag = "SL", Name = "Sierra Leone" },
			new stGeoCountry() { Id = 198,  Tag = "SM", Name = "San Marino" },
			new stGeoCountry() { Id = 199,  Tag = "SN", Name = "Senegal" },
			new stGeoCountry() { Id = 200,  Tag = "SO", Name = "Somalia" },
			new stGeoCountry() { Id = 201,  Tag = "SR", Name = "Suriname" },
			new stGeoCountry() { Id = 202,  Tag = "ST", Name = "Sao Tome and Principe" },
			new stGeoCountry() { Id = 203,  Tag = "SV", Name = "El Salvador" },
			new stGeoCountry() { Id = 204,  Tag = "SY", Name = "Syrian Arab Republic" },
			new stGeoCountry() { Id = 205,  Tag = "SZ", Name = "Swaziland" },
			new stGeoCountry() { Id = 206,  Tag = "TC", Name = "Turks and Caicos Islands" },
			new stGeoCountry() { Id = 207,  Tag = "TD", Name = "Chad" },
			new stGeoCountry() { Id = 208,  Tag = "TF", Name = "French Southern Territories" },
			new stGeoCountry() { Id = 209,  Tag = "TG", Name = "Togo" },
			new stGeoCountry() { Id = 210,  Tag = "TH", Name = "Thailand" },
			new stGeoCountry() { Id = 211,  Tag = "TJ", Name = "Tajikistan" },
			new stGeoCountry() { Id = 212,  Tag = "TK", Name = "Tokelau" },
			new stGeoCountry() { Id = 213,  Tag = "TM", Name = "Turkmenistan" },
			new stGeoCountry() { Id = 214,  Tag = "TN", Name = "Tunisia" },
			new stGeoCountry() { Id = 215,  Tag = "TO", Name = "Tonga" },
			new stGeoCountry() { Id = 216,  Tag = "TL", Name = "Timor-Leste" },
			new stGeoCountry() { Id = 217,  Tag = "TR", Name = "Turkey" },
			new stGeoCountry() { Id = 218,  Tag = "TT", Name = "Trinidad and Tobago" },
			new stGeoCountry() { Id = 219,  Tag = "TV", Name = "Tuvalu" },
			new stGeoCountry() { Id = 220,  Tag = "TW", Name = "Taiwan" },
			new stGeoCountry() { Id = 221,  Tag = "TZ", Name = "Tanzania, United Republic of" },
			new stGeoCountry() { Id = 222,  Tag = "UA", Name = "Ukraine" },
			new stGeoCountry() { Id = 223,  Tag = "UG", Name = "Uganda" },
			new stGeoCountry() { Id = 224,  Tag = "UM", Name = "United States Minor Outlying Islands" },
			new stGeoCountry() { Id = 225,  Tag = "US", Name = "United States" },
			new stGeoCountry() { Id = 226,  Tag = "UY", Name = "Uruguay" },
			new stGeoCountry() { Id = 227,  Tag = "UZ", Name = "Uzbekistan" },
			new stGeoCountry() { Id = 228,  Tag = "VA", Name = "Holy See (Vatican City State)" },
			new stGeoCountry() { Id = 229,  Tag = "VC", Name = "Saint Vincent and the Grenadines" },
			new stGeoCountry() { Id = 230,  Tag = "VE", Name = "Venezuela" },
			new stGeoCountry() { Id = 231,  Tag = "VG", Name = "Virgin Islands, British" },
			new stGeoCountry() { Id = 232,  Tag = "VI", Name = "Virgin Islands, U.S." },
			new stGeoCountry() { Id = 233,  Tag = "VN", Name = "Vietnam" },
			new stGeoCountry() { Id = 234,  Tag = "VU", Name = "Vanuatu" },
			new stGeoCountry() { Id = 235,  Tag = "WF", Name = "Wallis and Futuna" },
			new stGeoCountry() { Id = 236,  Tag = "WS", Name = "Samoa" },
			new stGeoCountry() { Id = 237,  Tag = "YE", Name = "Yemen" },
			new stGeoCountry() { Id = 238,  Tag = "YT", Name = "Mayotte" },
			new stGeoCountry() { Id = 239,  Tag = "RS", Name = "Serbia" },
			new stGeoCountry() { Id = 240,  Tag = "ZA", Name = "South Africa" },
			new stGeoCountry() { Id = 241,  Tag = "ZM", Name = "Zambia" },
			new stGeoCountry() { Id = 242,  Tag = "ME", Name = "Montenegro" },
			new stGeoCountry() { Id = 243,  Tag = "ZW", Name = "Zimbabwe" },
			new stGeoCountry() { Id = 244,  Tag = "A1", Name = "Anonymous Proxy" },
			new stGeoCountry() { Id = 245,  Tag = "A2", Name = "Satellite Provider" },
			new stGeoCountry() { Id = 246,  Tag = "O1", Name = "Other" },
			new stGeoCountry() { Id = 247,  Tag = "AX", Name = "Aland Islands" },
			new stGeoCountry() { Id = 248,  Tag = "GG", Name = "Guernsey" },
			new stGeoCountry() { Id = 249,  Tag = "IM", Name = "Isle of Man" },
			new stGeoCountry() { Id = 250,  Tag = "JE", Name = "Jersey" },
			new stGeoCountry() { Id = 251,  Tag = "BL", Name = "Saint Barthelemy" },
			new stGeoCountry() { Id = 252,  Tag = "MF", Name = "Saint Martin" },
			new stGeoCountry() { Id = 253,  Tag = "BQ", Name = "Bonaire, Saint Eustatius and Saba" },
			new stGeoCountry() { Id = 254,  Tag = "SS", Name = "South Sudan" },
			new stGeoCountry() { Id = 255,  Tag = "O1", Name = "Other" },
        };
	}
}
